title: Shuei's Blog
email: icethecat1337@gmail.com
description: My blog for posting everything
author: Shuei
baseurl: ""
url: "https://ice602.github.io"

# Social Profiles
twitter_username:
github_username: ice602
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
